### ISSUE TITLE
Rule that detects unused ports

### ISSUE THREAD

**Issue by jfmengels** [sparksp/elm-review-ports#1]
I think it would be useful to have a rule that checks whether a port is unused. This can crash people's applications, and is also a common problem that beginners run into but do not understand.

If this gets added, I think the package's documentation (in the README and in the elm.json at least) should change to say it's a general review package for rules, one way or another.

Thanks for making this package :heart:

**Comment by sparksp** [comment]
Here's a related issue for reference: https://github.com/elm/compiler/issues/1988

**Comment by sparksp** [comment]
I did some research into what counts as unused as part of developing the rule, here are the findings for the record.

## Findings
 - It does not matter whether the port is returned directly or via other function calls.
 - Being exposed from a module has no effect on its own.
 - A port is only made available when:
   - An outgoing port is returned from an application's `update`.
   - An incoming port is returned from an application's `subscriptions`.
 - When there are no available ports, `app.ports` is undefined.
 - There is no difference with or without `--optimize`.
